consumer_risk_engine:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', 'mock_account.us-east-1') }}"
      user: "{{ env_var('SNOWFLAKE_USER', 'mock_user') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', 'mock_password') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'SYSADMIN') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'CONSUMER_RISK_DB') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'COMPUTE_WH') }}"
      schema: staging
      threads: 4
      client_session_keep_alive: false
      query_tag: consumer_risk_engine_dbt

    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'SYSADMIN') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      schema: staging
      threads: 8
      client_session_keep_alive: false
      query_tag: consumer_risk_engine_dbt_prod
